import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Enable React strict mode for better development experience
  reactStrictMode: true,

  // Image optimization configuration
  images: {
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },

  // Security headers for SEO and security
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "X-DNS-Prefetch-Control",
            value: "on",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "X-Frame-Options",
            value: "SAMEORIGIN",
          },
          {
            key: "X-XSS-Protection",
            value: "1; mode=block",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(self)",
          },
        ],
      },
      // Cache static assets
      {
        source: "/images/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        source: "/:path*.ico",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
    ];
  },

  // Redirects for SEO - Old URLs to new structure
  async redirects() {
    return [
      // =====================================================
      // LOCATION URL STRUCTURE CHANGES
      // Old: /locations/[city] -> New: /mobile-detailing-[city]
      // =====================================================
      { source: "/locations/san-jose", destination: "/mobile-detailing-san-jose", permanent: true },
      { source: "/locations/santa-clara", destination: "/mobile-detailing-santa-clara", permanent: true },
      { source: "/locations/sunnyvale", destination: "/mobile-detailing-sunnyvale", permanent: true },
      { source: "/locations/mountain-view", destination: "/mobile-detailing-mountain-view", permanent: true },
      { source: "/locations/palo-alto", destination: "/mobile-detailing-palo-alto", permanent: true },
      { source: "/locations/cupertino", destination: "/mobile-detailing-cupertino", permanent: true },
      { source: "/locations/milpitas", destination: "/mobile-detailing-milpitas", permanent: true },
      { source: "/locations/fremont", destination: "/mobile-detailing-fremont", permanent: true },
      { source: "/locations/campbell", destination: "/mobile-detailing-campbell", permanent: true },
      { source: "/locations/los-gatos", destination: "/mobile-detailing-los-gatos", permanent: true },
      { source: "/locations/saratoga", destination: "/mobile-detailing-saratoga", permanent: true },
      { source: "/locations/san-francisco", destination: "/mobile-detailing-san-francisco", permanent: true },
      { source: "/locations/oakland", destination: "/mobile-detailing-oakland", permanent: true },
      { source: "/locations/san-benito-county", destination: "/mobile-detailing-san-benito-county", permanent: true },

      // =====================================================
      // OLD LEGITIMATE BLOG URLS -> SERVICE PAGES
      // Redirecting old WordPress blog URLs to relevant service pages
      // =====================================================
      { source: "/bring-back-the-shine-albros-premium-car-detailing", destination: "/services", permanent: true },
      { source: "/car-detaili-cost-guide", destination: "/services", permanent: true },
      { source: "/how-often-should-you-detail-your-car-guide", destination: "/blog/how-often-should-you-detail-your-car-california", permanent: true },
      { source: "/leather-car-seats-cleaning-santa-clara", destination: "/services#interior-detail", permanent: true },
      { source: "/car-odor-removal-eliminate-bad-smells", destination: "/services#interior-detail", permanent: true },

      // =====================================================
      // HACKED/SPAM URLS - Redirect to homepage
      // These were malware/spam pages created by hackers
      // Redirecting to homepage with 301 to clean up SEO
      // =====================================================
      { source: "/adobe-premiere-pro-portable-only-windows-10-full-gdrive", destination: "/", permanent: true },
      { source: "/lightwave-3d-portable-for-pc-lifetime-final-filehippo", destination: "/", permanent: true },
      { source: "/virtualdj-portable-serial-key-clean-x86x64-clean-verified", destination: "/", permanent: true },
      { source: "/adobe-premiere-pro-crack-portable-windows-10-x86x64-no-virus-2025", destination: "/", permanent: true },
      { source: "/adobe-after-effects-cracked-100-worked-x64-stable-reddit", destination: "/", permanent: true },
      { source: "/hdd-regenerator-crack-license-key-patch-patch-instant", destination: "/", permanent: true },
      { source: "/microsoft-office-portable-crack-latest-x86-x64-latest", destination: "/", permanent: true },
      { source: "/webull-desktop-pre-activated-final-clean-mega", destination: "/", permanent: true },
      { source: "/hitmanpro-portable-product-key-100-worked-clean-2025", destination: "/", permanent: true },
      { source: "/adobe-after-effects-portable-crack-latest-x86x64-windows-2025", destination: "/", permanent: true },
      { source: "/ibm-spss-statisticsbase-pre-activated-all-versions-x86x64-full-zip", destination: "/", permanent: true },
      { source: "/transmac-crack-product-key-full-stable-2025", destination: "/", permanent: true },
      { source: "/endnote-full-license-portable-activator-stable-x32x64-no-virus-2025", destination: "/", permanent: true },
      { source: "/filmora-portable-product-key-lifetime-x86x64-clean-zip", destination: "/", permanent: true },
      { source: "/dvd-cloner-portable-exe-lifetime-100-worked-ultimate", destination: "/", permanent: true },
      { source: "/sketchup-vray-portable-keygen-lifetime-x32-x64-100-worked-filehippo", destination: "/", permanent: true },
      { source: "/sketchup-crack-windows-11-full-unlimited", destination: "/", permanent: true },
      { source: "/sondle-screenshot-keylogger-portable-crack-full-x32x64-stable", destination: "/", permanent: true },
      { source: "/topaz-ai-7-crack-license-key-no-virus-x86-x64-latest-tested", destination: "/", permanent: true },
      { source: "/microsoft-onedrive-full-activated-patch-x86-x64-clean", destination: "/", permanent: true },
      { source: "/vegas-pro-21-crack-serial-key-full-x86x64-patch-zip", destination: "/", permanent: true },
      { source: "/internet-download-manager-idm-portable-for-pc-clean-x32-x64-final-premium", destination: "/", permanent: true },
      { source: "/plagiarism-detector-crack-serial-key-full-x86x64-patch-zip", destination: "/", permanent: true },
      { source: "/endnote-full-license-portable-only-latest-x86x64-final-filehippo", destination: "/", permanent: true },
      { source: "/kmspico-office-pre-activated-lifetime-x86x64-full-unlimited", destination: "/", permanent: true },
      { source: "/earthview-crack-portable-all-versions-x32-x64-full", destination: "/", permanent: true },
      { source: "/panda-dome-advanced-licenseactivated-latest-no-virus-github", destination: "/", permanent: true },
      { source: "/youtube-browser-licenseactivated-latest-no-virus-github", destination: "/", permanent: true },
      { source: "/ssdlife-family-commercial-crack-portable-latest-100-worked-2024", destination: "/", permanent: true },
      { source: "/microsoft-word-2024-portable-exe-latest-x32x64-clean-2025", destination: "/", permanent: true },
      { source: "/vegas-pro-22-crack-latest-windows-11-mediafire", destination: "/", permanent: true },
      { source: "/directory-opus-portable-crack-patch-patch-filehippo", destination: "/", permanent: true },
      { source: "/teamviewer-portable-crack-windows-11-100-worked-2025", destination: "/", permanent: true },
      { source: "/0x1aa4ccbe", destination: "/", permanent: true },
      { source: "/progdvb-licenseactivated-stable-lifetime-2025", destination: "/", permanent: true },
      { source: "/bulk-image-downloader-crack-keygen-windows-x32-x64-clean-2024", destination: "/", permanent: true },
      { source: "/win2pdf-pro-activated-patch-x32x64-no-virus-github", destination: "/", permanent: true },
      { source: "/remote-anything-portable-only-stable-final", destination: "/", permanent: true },
      { source: "/autocad-full-activated-final-patch-verified", destination: "/", permanent: true },
      { source: "/folder-guard-portable-keygen-windows-latest-tested", destination: "/", permanent: true },
      { source: "/internet-download-manager-idm-2024-crack-clean-x86-x64-100-worked-premium", destination: "/", permanent: true },
      { source: "/solidworks-2021-crack-portable-no-virus-patch-genuine", destination: "/", permanent: true },
      { source: "/ace-utilities-portable-exe-patch-stable", destination: "/", permanent: true },
      { source: "/fl-studio-2023-cracked-windows-final-instant", destination: "/", permanent: true },
      { source: "/anydesk-premium-crack-keygen-clean-x32x64-final", destination: "/", permanent: true },
      { source: "/total-uninstall-crack-license-key-lifetime-x86-x64-latest-premium", destination: "/", permanent: true },
      { source: "/coreldraw-x8-portable-only-all-versions-x32-x64-lifetime-mediafire", destination: "/", permanent: true },
      { source: "/google-maps-downloader-crack-portable-stable-latest-tested", destination: "/", permanent: true },
      { source: "/mindjet-mindmanager-professional-crack-license-key-latest-x32x64-100-worked", destination: "/", permanent: true },
      { source: "/stop-p-o-r-n-cracked-patch-100-worked-github", destination: "/", permanent: true },
      { source: "/panda-dome-advanced-portable-for-pc-final-x64-clean-mediafire", destination: "/", permanent: true },
      { source: "/sketchup-2022-pre-activated-latest-final-2025", destination: "/", permanent: true },
      { source: "/virtualdj-pro-freeactivated-full-x64-windows-filecr", destination: "/", permanent: true },
      { source: "/office-365-crack-serial-key-final-x86-x64-final-filecr", destination: "/", permanent: true },
      { source: "/nice-pdf-compressor-cracked-final-x86x64-lifetime-filecr", destination: "/", permanent: true },
      { source: "/filmora-freeactivated-lifetime-x32x64-latest", destination: "/", permanent: true },
      { source: "/lumion-2024-crack-keygen-stable-100-worked-github", destination: "/", permanent: true },
      { source: "/fl-studio-2025-crack-exe-universal-no-virus", destination: "/", permanent: true },
      { source: "/anti-porn-crack-serial-key-lifetime-x86-x64-lifetime", destination: "/", permanent: true },
      { source: "/mcafee-visual-trace-portable-keygen-patch-x32-x64-clean-mediafire", destination: "/", permanent: true },
      { source: "/trade-ideas-tradewaves-full-activated-full-full-gdrive", destination: "/", permanent: true },
      { source: "/topaz-ai-portable-serial-key-no-virus-x32x64-windows-10-tested", destination: "/", permanent: true },
      { source: "/easeus-data-recovery-19-portable-latest-patch-2025", destination: "/", permanent: true },
      { source: "/gridinsoft-anti-malware-portable-latest-patch-2025", destination: "/", permanent: true },
      { source: "/ultraiso-cracked-no-virus-x86x64-latest-tested", destination: "/", permanent: true },
      { source: "/easeus-data-recovery-2025-cracked-no-virus-x86x64-latest-tested", destination: "/", permanent: true },
      { source: "/newsbin-pro-with-internet-search-crack-keygen-final-final-zip", destination: "/", permanent: true },
      { source: "/sketchup-pro-activated-stable-stable-gdrive", destination: "/", permanent: true },
      { source: "/snappy-fax-portable-activator-windows-x64-clean-filehippo", destination: "/", permanent: true },
      { source: "/google-maps-downloader-crack-tool-100-worked-x32x64-patch-filehippo", destination: "/", permanent: true },
      { source: "/cyberghost-activated-final-full-ultimate", destination: "/", permanent: true },
      { source: "/topaz-ai-portable-keygen-full-windows-10-mediafire", destination: "/", permanent: true },
      { source: "/newsbin-pro-with-internet-search-crack-tool-all-versions-clean-multilingual", destination: "/", permanent: true },
      { source: "/adobe-illustrator-2024-freeactivated-100-worked-no-virus-2024", destination: "/", permanent: true },
      { source: "/adobe-acrobat-2025-cracked-clean-x32-x64-patch-genuine", destination: "/", permanent: true },
      { source: "/kmspico-auto-crack-exe-latest-no-virus-gdrive", destination: "/", permanent: true },
      { source: "/pc-maclan-crack-exe-latest-no-virus-gdrive", destination: "/", permanent: true },
      { source: "/ocr-image-to-text-conversion-tool-crack-exe-latest-no-virus-gdrive", destination: "/", permanent: true },
      { source: "/matlab-crack-tool-patch-x86x64-100-worked-ultimate", destination: "/", permanent: true },
      { source: "/vmware-workstation-portable-activator-full-patch-2025", destination: "/", permanent: true },
      { source: "/remote-anything-crack-license-key-clean-x64-stable-mega", destination: "/", permanent: true },
      { source: "/winhex-crack-100-worked-x86-x64-stable-instant", destination: "/", permanent: true },
      { source: "/office-365-portable-latest-clean-gdrive", destination: "/", permanent: true },
      { source: "/pc-maclan-licenseactivated-lifetime-x32-x64-lifetime-mega", destination: "/", permanent: true },
      { source: "/google-satellite-maps-downloader-crack-license-key-lifetime-x32-x64-100-worked-zip", destination: "/", permanent: true },
      { source: "/rithmic-licenseactivated-windows-10-x32x64-stable", destination: "/", permanent: true },
      { source: "/winrar-activated-patch-windows-2025", destination: "/", permanent: true },
      { source: "/able2extract-professional-cracked-all-versions-stable-genuine", destination: "/", permanent: true },
      { source: "/internet-download-manager-idm-6-41-crack-serial-key-clean-x86-x64-patch-genuine", destination: "/", permanent: true },
      { source: "/teamviewer-premium-pre-activated-stable-no-virus-filehippo", destination: "/", permanent: true },
      { source: "/ableton-live-2024-freeactivated-100-worked-x64-clean-2025", destination: "/", permanent: true },
      { source: "/elite-proxy-switcher-portable-license-key-patch-x64-latest-gdrive", destination: "/", permanent: true },
      { source: "/lumion-2025-portable-crack-patch-full-gdrive", destination: "/", permanent: true },
      { source: "/adobe-photoshop-full-activated-100-worked-lifetime-tested", destination: "/", permanent: true },
      { source: "/microsoft-excel-freeactivated-lifetime-x86-x64-final-tested", destination: "/", permanent: true },
      { source: "/anydesk-professional-portable-exe-100-worked-x32x64-clean-tested", destination: "/", permanent: true },
      { source: "/vegas-pro-2025-crack-for-pc-full-100-worked-multilingual", destination: "/", permanent: true },
      { source: "/treesize-professional-treesize-ultrasearch-professional-license-portable-tool-windows-x64-lifetime-unlimited", destination: "/", permanent: true },
      { source: "/filmora-crack-license-key-latest-x86-x64-patch-verified", destination: "/", permanent: true },
      { source: "/word-excel-powerpoint-to-pdf-converter-crack-keygen-universal-x64-100-worked-filehippo", destination: "/", permanent: true },
      { source: "/transtools-activated-clean-x64-windows-verified", destination: "/", permanent: true },
      { source: "/eset-nod32-antivirus-home-security-essential-internet-security-crack-exe-no-virus-latest-verified", destination: "/", permanent: true },
      { source: "/recuva-data-recovery-portable-product-key-patch-x86x64-100-worked-genuine", destination: "/", permanent: true },
      { source: "/vegas-pro-twixtor-crack-keygen-windows-10-x32x64-stable-zip", destination: "/", permanent: true },
      { source: "/doc-to-image-converter-licenseactivated-latest-windows-11-premium", destination: "/", permanent: true },
      { source: "/solidworks-2022-crack-exe-100-worked-stable-unlimited", destination: "/", permanent: true },
      { source: "/rankit-crack-license-key-no-virus-patch-github", destination: "/", permanent: true },
      { source: "/adguard-crack-portable-final-stable", destination: "/", permanent: true },
      { source: "/xyplorer-license-pro-crack-license-key-no-virus-x32x64-full-multilingual", destination: "/", permanent: true },
      { source: "/softperfect-network-scanner-portable-crack-final-x86-x64-100-worked-filecr", destination: "/", permanent: true },
      { source: "/puffin-browser-business-crack-exe-no-virus-windows-multilingual", destination: "/", permanent: true },
      { source: "/simple-port-forwarding-portable-license-key-patch-x64-final", destination: "/", permanent: true },
      { source: "/kmspico-auto-portable-tool-final-windows", destination: "/", permanent: true },
      { source: "/adobe-illustrator-crack-keygen-full-x64-final-2025", destination: "/", permanent: true },
      { source: "/bionix-wallpaper-portable-keygen-windows-final-filehippo", destination: "/", permanent: true },
      { source: "/microsoft-excel-portable-activator-windows-10-no-virus-github", destination: "/", permanent: true },
      { source: "/easeus-data-recovery-15-crack-portable-100-worked-windows-11-2025", destination: "/", permanent: true },
      { source: "/adobe-illustrator-cc-crack-serial-key-windows-11-x32x64-windows-tested", destination: "/", permanent: true },
      { source: "/sierra-chart-portable-keygen-no-virus-x86-x64-no-virus-filehippo", destination: "/", permanent: true },
      // Office spam URLs
      { source: "/office-365-mondo-x86-v16-89-portable-tiny-xrg-magnet-link", destination: "/", permanent: true },
      { source: "/ms-office-365-pro-plus-pre-activated-v16-89-to%f0%9d%9a%9brent-dow%f0%9d%9a%97l%f0%9d%9a%98ad", destination: "/", permanent: true },
      { source: "/office-2026-ltsc-standard-64-bit-v16-89-optimized-eztv-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/m365-32-bit-full-version-italian-original-iso-no-online-sign-in-monarch-to%f0%9d%9a%9brent-dow%f0%9d%9a%97l%f0%9d%9a%98ad", destination: "/", permanent: true },
      { source: "/ms-ms-office-32-bit-cracked-russian-v16-89-ctrlhd-magnet-link", destination: "/", permanent: true },
      { source: "/office-2019-pro-plus-32-bit-install-package-heidoc-slim-kms-vl-all-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-ltsc-64-bit-french-most-recent-version-without-onedrive-super-lite-m0nkrus-magnet-link", destination: "/", permanent: true },
      { source: "/office-365-32-bit-archive-yts-magnet-link", destination: "/", permanent: true },
      { source: "/office-2021-internet-archive-atmos-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/microsoft-office-2024-64bits-multilanguage-without-bloatware-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2021-officially-activated-silent-setup-vlsc-qxr-direct-download", destination: "/", permanent: true },
      { source: "/m365-pre-cracked-setup64-exe-italian-v2408-no-copilot-compact-build-m0nkrus-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/microsoft-office-2016-direct-link-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2016-crack-no-hardware-checks-rarbg-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/m365-enterprise-e3-activation-included-german-gaming-edition-p2p-direct-download", destination: "/", permanent: true },
      { source: "/ms-office-2016-business-basic-x64-x86-activation-included-latest-ctrlhd-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/m365-business-basic-italian-retail-compact-build-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/ms-ms-office-polish-to%f0%9d%9a%9brent-dow%f0%9d%9a%97l%f0%9d%9a%98ad", destination: "/", permanent: true },
      { source: "/m365-cracked-multilanguage-latest-yts-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/ms-ms-office-professional-64-bit-offline-setup-heidoc-yify-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2021-business-basic-64-bit-direct-iso-updated-minimal-setup-atmos-direct-download", destination: "/", permanent: true },
      { source: "/office-365-x64-fully-cracked-deployment-tool-v2408-ctrlhd-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2016-64bits-mediafire-newest-release-super-fast-direct-download", destination: "/", permanent: true },
      { source: "/office-2021-ltsc-pro-plus-crack-original-iso-rarbg-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/ms-office-2025-32-bit-auto-crack-odt-compact-build-yify-to%f0%9d%9a%9brent-dow%f0%9d%9a%97l%f0%9d%9a%98ad", destination: "/", permanent: true },
      { source: "/ms-office-2026-one-click-setup-reddit-lite-eztv-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/m365-x86-pre-activated-exe-file-archive-yify-direct-download", destination: "/", permanent: true },
      { source: "/ms-office-2016-x64-direct-iso-french-super-fast-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/microsoft-office-2016-arm64-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/m365-arm64-updated-yify-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-365-professional-plus-arm64-lifetime-activated-github-p2p-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2019-small-business-silent-activation-no-defender-check-eztv-get-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2021-home-business-super-fast-monarch-direct-download", destination: "/", permanent: true },
      { source: "/office-2025-x64-oinstall-exe-direct-link-no-background-services-magnet-link", destination: "/", permanent: true },
      { source: "/ms-microsoft-365-premium-64bits-install-wizard-german-latest-without-bloatware-debloated-eztv-get-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/microsoft-office-2021-professional-64-install-wizard-super-lite-bypass-hardware-check-atmos-magnet-link", destination: "/", permanent: true },
      { source: "/microsoft-office-2021-arm64-cracked-one-click-setup-stable-get-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2025-personal-x64-setup-only-latest-team-os-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2026-professional-activation-included-odt-slim-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2016-x86-patched-offline-setup-direct-link-original-iso-direct-download", destination: "/", permanent: true },
      { source: "/microsoft-365-business-massgrave-archive-no-cloud-integration-slim-direct-download", destination: "/", permanent: true },
      { source: "/microsoft-365-vl-edition-offline-setup-mediafire-no-online-sign-in-ultra-lite-edition-ctrlhd-get-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2016-arm-patched-github-tiny-get-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/microsoft-office-2021-pro-plus-multilanguage-account-free-setup-super-fast-magnet-link", destination: "/", permanent: true },
      { source: "/office-2019-small-business-arm64-odt-latest-build-portable-optimized-eztv-magnet-link", destination: "/", permanent: true },
      { source: "/ms-ms-office-arm64-kms-activated-super-lite-direct-download", destination: "/", permanent: true },
      { source: "/m365-standard-arm64-internet-archive-most-recent-version-tiny-magnet-link", destination: "/", permanent: true },
      { source: "/office-2025-x64-x86-massgrave-odt-github-super-lite-p2p-to%f0%9d%9a%9brent-dow%f0%9d%9a%97l%f0%9d%9a%98ad", destination: "/", permanent: true },
      { source: "/microsoft-office-365-pro-plus-google-drive-rarbg-to%f0%9d%9a%9brent-dow%f0%9d%9a%97l%f0%9d%9a%98ad", destination: "/", permanent: true },
      { source: "/office-2016-fully-activated-french-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2024-silent-activation-google-drive-updated-debloated-yify-magnet-link", destination: "/", permanent: true },
      { source: "/microsoft-office-2025-arm-heidoc-original-iso-no-defender-check-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/microsoft-365-enterprise-e5-v16-89-no-hardware-checks-rarbg-dow%f0%9d%9a%97l%f0%9d%9a%98ad-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-2019-arm64-fully-cracked-setup-file-bypass-hardware-check-debloated-ctrlhd-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/ms-office-2025-64bits-fully-cracked-exe-file-super-lite-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/office-ltsc-enterprise-e3-x86-lifetime-activated-without-onedrive-p2p-get-to%f0%9d%9a%9brent", destination: "/", permanent: true },
      { source: "/ms-office-2024-32-bit-no-serial-needed-spanish-updated-ctrlhd-direct-download", destination: "/", permanent: true },

      // =====================================================
      // CATCH-ALL FOR ANY OTHER SPAM PATTERNS
      // Using wildcard patterns for common spam URL patterns
      // =====================================================
      { source: "/:path*crack:rest*", destination: "/", permanent: true },
      { source: "/:path*keygen:rest*", destination: "/", permanent: true },
      { source: "/:path*portable-exe:rest*", destination: "/", permanent: true },
      { source: "/:path*torrent:rest*", destination: "/", permanent: true },
      { source: "/:path*magnet-link:rest*", destination: "/", permanent: true },
    ];
  },
};

export default nextConfig;
